package es.app.attune.attune.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ATT_PLAYLIST".
*/
public class AttPlaylistDao extends AbstractDao<AttPlaylist, String> {

    public static final String TABLENAME = "ATT_PLAYLIST";

    /**
     * Properties of entity AttPlaylist.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tempo = new Property(2, float.class, "tempo", false, "TEMPO");
        public final static Property Duration = new Property(3, int.class, "duration", false, "DURATION");
        public final static Property Image = new Property(4, String.class, "image", false, "IMAGE");
        public final static Property Genre = new Property(5, String.class, "genre", false, "GENRE");
        public final static Property Creation_date = new Property(6, java.util.Date.class, "creation_date", false, "CREATION_DATE");
    }

    private DaoSession daoSession;


    public AttPlaylistDao(DaoConfig config) {
        super(config);
    }
    
    public AttPlaylistDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ATT_PLAYLIST\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"TEMPO\" REAL NOT NULL ," + // 2: tempo
                "\"DURATION\" INTEGER NOT NULL ," + // 3: duration
                "\"IMAGE\" TEXT," + // 4: image
                "\"GENRE\" TEXT NOT NULL ," + // 5: genre
                "\"CREATION_DATE\" INTEGER NOT NULL );"); // 6: creation_date
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ATT_PLAYLIST_ID ON \"ATT_PLAYLIST\"" +
                " (\"ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ATT_PLAYLIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AttPlaylist entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getName());
        stmt.bindDouble(3, entity.getTempo());
        stmt.bindLong(4, entity.getDuration());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(5, image);
        }
        stmt.bindString(6, entity.getGenre());
        stmt.bindLong(7, entity.getCreation_date().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AttPlaylist entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getName());
        stmt.bindDouble(3, entity.getTempo());
        stmt.bindLong(4, entity.getDuration());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(5, image);
        }
        stmt.bindString(6, entity.getGenre());
        stmt.bindLong(7, entity.getCreation_date().getTime());
    }

    @Override
    protected final void attachEntity(AttPlaylist entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public AttPlaylist readEntity(Cursor cursor, int offset) {
        AttPlaylist entity = new AttPlaylist( //
            cursor.getString(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getFloat(offset + 2), // tempo
            cursor.getInt(offset + 3), // duration
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // image
            cursor.getString(offset + 5), // genre
            new java.util.Date(cursor.getLong(offset + 6)) // creation_date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AttPlaylist entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setTempo(cursor.getFloat(offset + 2));
        entity.setDuration(cursor.getInt(offset + 3));
        entity.setImage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGenre(cursor.getString(offset + 5));
        entity.setCreation_date(new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final String updateKeyAfterInsert(AttPlaylist entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(AttPlaylist entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AttPlaylist entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
