package es.app.attune.attune.Database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import es.app.attune.attune.Database.Genre;
import es.app.attune.attune.Database.Playlist;
import es.app.attune.attune.Database.Song;

import es.app.attune.attune.Database.GenreDao;
import es.app.attune.attune.Database.PlaylistDao;
import es.app.attune.attune.Database.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig genreDaoConfig;
    private final DaoConfig playlistDaoConfig;
    private final DaoConfig songDaoConfig;

    private final GenreDao genreDao;
    private final PlaylistDao playlistDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        playlistDaoConfig = daoConfigMap.get(PlaylistDao.class).clone();
        playlistDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        genreDao = new GenreDao(genreDaoConfig, this);
        playlistDao = new PlaylistDao(playlistDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(Genre.class, genreDao);
        registerDao(Playlist.class, playlistDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        genreDaoConfig.clearIdentityScope();
        playlistDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

    public PlaylistDao getPlaylistDao() {
        return playlistDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
