package es.app.attune.attune.database;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attPlaylistDaoConfig;
    private final DaoConfig genreDaoConfig;
    private final DaoConfig songDaoConfig;

    private final AttPlaylistDao attPlaylistDao;
    private final GenreDao genreDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attPlaylistDaoConfig = daoConfigMap.get(AttPlaylistDao.class).clone();
        attPlaylistDaoConfig.initIdentityScope(type);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        attPlaylistDao = new AttPlaylistDao(attPlaylistDaoConfig, this);
        genreDao = new GenreDao(genreDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(AttPlaylist.class, attPlaylistDao);
        registerDao(Genre.class, genreDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        attPlaylistDaoConfig.clearIdentityScope();
        genreDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public AttPlaylistDao getAttPlaylistDao() {
        return attPlaylistDao;
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
